### ISSUE TITLE
Black Tab in the Menu

### ISSUE THREAD

**Issue by fsalam90** [Crymzix/Pretzel#16]
There is way to remove the black tab that is visible when we slide the slide-menu back and forth. Somehow the system thinks the button is pressed(Like an on-off switch where is kept pressed on) which is why the dark tab stays. In other apps, the menu items are pressed once and the item disappears and take you to the new screen (like pressing a doorbell)...Chris Li Please seek an option like the latter. Thanks!

I have checked this update on the Tinder app and its looks neater. 

Also for the person to know where he/she is, I think the Label on top of the screen is helpful enough.

**Comment by Crymzix** [comment]
Yes I do see that this kind of implementation in the Tinder app but the difference in their app and ours is that in our app, the user is more likely to navigate between sections of the app more frequently and thus they will be opening the drawer more often. The graphical issue that your are trying to mitigate is only happening on your device and most likely wouldn't be affecting the majority of the devices that the app will be running on so doing such a change that goes against design guidelines (as set out by Google) doesn't seem to be the best idea. As a compromise I have removed the black pressed state and added a white indicator to the left of the menu item.
