### ISSUE TITLE
Main Logo

### ISSUE THREAD

**Issue by Crymzix** [Crymzix/Pretzel#2]
The main logo should have the black box around it just like the photo I sent you.

**Comment by fsalam90** [comment]
![roundlogo](https://cloud.githubusercontent.com/assets/13363614/8730607/b749ce5e-2ba6-11e5-9b9c-67d90cb5e069.png)

**Comment by fsalam90** [comment]
i think we should incorporate this one instead. Otherwise the previous logo looked a lot like Uber

**Comment by fsalam90** [comment]
![logo 2](https://cloud.githubusercontent.com/assets/13363614/8771402/1943b1fc-2e76-11e5-9d77-79e3df6a54e6.png)
