### ISSUE TITLE
Question on status regulation!

### ISSUE THREAD

**Issue by fsalam90** [Crymzix/Pretzel#26]
I was hoping if you could please tell me about how the posts are regulated. For example, if someone posts a random status which is not about food or anything, will the system detect it by itself or will it stay visible until someone reports it?

**Comment by Crymzix** [comment]
No a reporting system is not in place. It will be a feature request. There's no efficient way to figure out whether or not a post is food related or not accurately. That would require machine learning and a lot of work that we do not have the time or resources for as most real world applications do not even have that kind of capability unless that have the manpower and data sets to do so. The best way to do this is just implement a reporting system.
