### ISSUE TITLE
Glitch in Transactions Page

### ISSUE THREAD

**Issue by fsalam90** [Crymzix/Pretzel#35]
When you refresh the Transactions page, you see brief glimpses of the previous logo. This has to be removed.

**Comment by fsalam90** [comment]
Chris could you please explain what you mean by the tag "can't reproduce"? I just checked that this glitch is still present in the recent build you sent me.

**Comment by Crymzix** [comment]
Okay, well what do you mean by "brief glimpses of the previous logo"? Which logo? It's not clear what you're describing.

**Comment by fsalam90** [comment]
remember the Yellow Chefs Hat logo???? that keeps appearing and disappearing (hence brief glimpses) when  I refresh the Transactions page!
