### ISSUE TITLE
Display pop-up style error message

### ISSUE THREAD

**Issue by fsalam90** [Crymzix/Pretzel#47]
when requesting yourself or trying to send a message to yourself, an error message must pop up saying "You cannot send a request to yourself" or "You cannot message yourself" respectively.

**Comment by Crymzix** [comment]
Simpler to just remove the buttons if it's your own post.

**Comment by fsalam90** [comment]
Yeap for the own post, it makes sense to delete the message and request button and just kep the Details button BUT please make sure to centre it!
