### ISSUE TITLE
Message Notification 

### ISSUE THREAD

**Issue by fsalam90** [Crymzix/Pretzel#5]
#5

After every sent message, a "Message has been sent" notification appears...I feel like this is redundant. ALSO If someone messages you, you get the notification on top TWICE.
Also the Icon is not fully visible when a request notification is made.

**Comment by Crymzix** [comment]
Please refrain from posting issues like this. They should all really be separate issues.

**Comment by fsalam90** [comment]
Point duely noted. My apologies for any inconvenience.
